// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/code_generator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeGenerator_GenerateCode_FullMethodName = "/codegenerator.CodeGenerator/GenerateCode"
)

// CodeGeneratorClient is the client API for CodeGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeGeneratorClient interface {
	GenerateCode(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type codeGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeGeneratorClient(cc grpc.ClientConnInterface) CodeGeneratorClient {
	return &codeGeneratorClient{cc}
}

func (c *codeGeneratorClient) GenerateCode(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CodeGenerator_GenerateCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeGeneratorServer is the server API for CodeGenerator service.
// All implementations must embed UnimplementedCodeGeneratorServer
// for forward compatibility.
type CodeGeneratorServer interface {
	GenerateCode(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedCodeGeneratorServer()
}

// UnimplementedCodeGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeGeneratorServer struct{}

func (UnimplementedCodeGeneratorServer) GenerateCode(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCode not implemented")
}
func (UnimplementedCodeGeneratorServer) mustEmbedUnimplementedCodeGeneratorServer() {}
func (UnimplementedCodeGeneratorServer) testEmbeddedByValue()                       {}

// UnsafeCodeGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeGeneratorServer will
// result in compilation errors.
type UnsafeCodeGeneratorServer interface {
	mustEmbedUnimplementedCodeGeneratorServer()
}

func RegisterCodeGeneratorServer(s grpc.ServiceRegistrar, srv CodeGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedCodeGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeGenerator_ServiceDesc, srv)
}

func _CodeGenerator_GenerateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeGeneratorServer).GenerateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeGenerator_GenerateCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeGeneratorServer).GenerateCode(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeGenerator_ServiceDesc is the grpc.ServiceDesc for CodeGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codegenerator.CodeGenerator",
	HandlerType: (*CodeGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCode",
			Handler:    _CodeGenerator_GenerateCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/code_generator.proto",
}
