// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/code_generator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_code_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_code_generator_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Expire        string                 `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_code_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_code_generator_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Response) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

var File_proto_code_generator_proto protoreflect.FileDescriptor

const file_proto_code_generator_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/code_generator.proto\x12\rcodegenerator\"\t\n" +
	"\aRequest\"6\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\tR\x06expire2P\n" +
	"\rCodeGenerator\x12?\n" +
	"\fGenerateCode\x12\x16.codegenerator.Request\x1a\x17.codegenerator.ResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_code_generator_proto_rawDescOnce sync.Once
	file_proto_code_generator_proto_rawDescData []byte
)

func file_proto_code_generator_proto_rawDescGZIP() []byte {
	file_proto_code_generator_proto_rawDescOnce.Do(func() {
		file_proto_code_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_code_generator_proto_rawDesc), len(file_proto_code_generator_proto_rawDesc)))
	})
	return file_proto_code_generator_proto_rawDescData
}

var file_proto_code_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_code_generator_proto_goTypes = []any{
	(*Request)(nil),  // 0: codegenerator.Request
	(*Response)(nil), // 1: codegenerator.Response
}
var file_proto_code_generator_proto_depIdxs = []int32{
	0, // 0: codegenerator.CodeGenerator.GenerateCode:input_type -> codegenerator.Request
	1, // 1: codegenerator.CodeGenerator.GenerateCode:output_type -> codegenerator.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_code_generator_proto_init() }
func file_proto_code_generator_proto_init() {
	if File_proto_code_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_code_generator_proto_rawDesc), len(file_proto_code_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_code_generator_proto_goTypes,
		DependencyIndexes: file_proto_code_generator_proto_depIdxs,
		MessageInfos:      file_proto_code_generator_proto_msgTypes,
	}.Build()
	File_proto_code_generator_proto = out.File
	file_proto_code_generator_proto_goTypes = nil
	file_proto_code_generator_proto_depIdxs = nil
}
